#!/usr/bin/env python
# -*- coding:utf-8 -*-
import urllib
import urllib2
import re
import thread
import time
import MySQLdb


class LP:

    def __init__(self):
        self.pageIndex = 0
        self.user_agent = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'
        self.headers = {'User-Agent' :self.user_agent}
        self.list = []


    def getPage(self,pageIndex):
        try:
            url = 'https://www.liepin.com/zhaopin/?pubTime=&ckid=2ed3502a04e2373f&fromSearchBtn=2&compkind=&isAnalysis=&init=-1&searchType=1&dqs=020&industryType=&jobKind=&sortFlag=15&industries=&salary=&compscale=&key=%E4%BC%9A%E8%AE%A1&clean_condition=&headckid=2ed3502a04e2373f&curPage=' + str(pageIndex)
            request = urllib2.Request(url,headers=self.headers)
            response = urllib2.urlopen(request)
            pageCode = response.read().decode('utf-8')

            return pageCode
        except urllib2.URLError,e:
            if hasattr(e,"reason"):
                print "error",e.reason
                return None

    def getPageItems(self,pageIndex):
        pageCode = self.getPage(pageIndex)
        if not pageCode:
            print "page load error"
            return None
        pattern = re.compile('<h3 title="(.*?)">.*?href="https://(.*?)".*?<p class="condition clearfix".*?title="(.*?)">.*?<span class="text-warning">(.*?)</span>.*?<span class="edu">(.*?)</span>.*?<span>(.*?)</span>.*?<a title="(.*?)"',re.S)

        items = re.findall(pattern,pageCode)
        pagelist = []
        for item in items:
            pagelist.append([item[0].strip(),item[1].strip(),item[2].strip(),item[3].strip(),item[4].strip(),item[5].strip(),item[6].strip()])
            print(item[0])
            print(item[1])
            print(item[2])
            print(item[3])
            print(item[4])
            print(item[5])
            b=item[6].replace("'",'')#以字符串形式去除替换掉'符号，因为这符号插入MYSQL有错
            print(b)

            conn= MySQLdb.connect(
            host='localhost',
            port = 3306,
            user='root',
            passwd='94159415',
            db ='zhaop',
            charset='utf8'
        )
            cur = conn.cursor()

            cur.execute("insert into pan VALUES (NULL,'%s','%s','%s','%s','%s','%s','%s')"%(item[0],item[1],item[2],item[3],item[4],item[5],b))

            cur.close()
            conn.commit()
            conn.close()
        return pagelist

    def loadPage(self):
        if len(self.list)<2:
            pagelist = self.getPageItems(self.pageIndex)
            if pagelist:
                self.list.append(pagelist)
                self.pageIndex +=1


    def start(self):
        print u'正在读取'
        self.loadPage()
        nowPage = 0
        pagelist = self.list[0]
        while nowPage<100:
                nowPage +=1
                del self.list[0]
                self.loadPage()


spider = LP()
spider.start()
